apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.argocdapp.spec.project | default "default" }}
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
      name: in-cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - "argocd"
    - "cad"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocdapp.spec.name | default "test" }}
  namespace: {{ .Values.argocdapp.argoNamespace | default "argocd" }}
  labels:
    {{- toYaml .Values.argocdapp.labels | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: {{ .Values.argocdapp.spec.project | default "default" }}
  destination:
    namespace: {{ .Values.argocdapp.spec.namespace | default "dev" }}
    server: {{ .Values.argocdapp.destinationServer | default .Values.argocdapp.spec.destination.server }}
  sources:
      {{- toYaml .Values.argocdapp.spec.sources | nindent 4 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true