argocdapp:
  destinationServer: ''
  argoProjectNamespace: ''
  argoNamespace: ''

  labels:
    env: dev
  spec:
    destination:
      server: https://kubernetes.default.svc
    project: cad
    namespace: cad
    sources:
      - repoURL: 'git@github.com:uc-cdis/gen3-helm.git'
        path: helm/gen3
        targetRevision: main
        helm:
          valueFiles:
            - $values/environments/dev/gen3-values.yaml
            - $values/environments/dev/secrets-values.yaml
      - repoURL: 'git@github.com:flashguerdon/gen3-workloads-example.git'
        targetRevision: main
        ref: values